import type { Metadata } from "next";
import Link from "next/link";
import CommercialPage from "@/components/CommercialPage";
import { legalOperator, publicContact, supportMailto } from "@/lib/publicContact";

export const metadata: Metadata = {
  title: "Politica de Confidențialitate | Povestea Mea Magică",
  description: "Cum sunt folosite și protejate datele de personalizare în Povestea Mea Magică.",
  alternates: { canonical: "/politica-de-confidentialitate" },
};

export default function PrivacyPage() {
  return <CommercialPage eyebrow="Confidențialitate" title="Datele voastre au un singur rol: să ajute la crearea materialului." description="Nu construim profiluri despre familie sau copil și nu cerem informații sensibile pentru a genera un PDF personalizat.">
    <section className="px-6 py-16 md:py-20"><div className="mx-auto max-w-5xl divide-y divide-brand-navy/15 border-y border-brand-navy/15 text-base font-medium leading-relaxed text-brand-navy/70">
      <section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Operatorul datelor</h2><p>Operatorul este <strong>{legalOperator.name}</strong>, CUI {legalOperator.cui}, nr. Registrul Comerțului {legalOperator.tradeRegisterNumber}, cu sediul social în {legalOperator.registeredOffice}. Pentru solicitări privind datele personale ne poți scrie la {publicContact.email}.</p></section>
      <section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Ce date folosim</h2><div><p>Poți introduce numele și vârsta copilului, preferințe, tema poveștii, o dedicație, un context de așteptare sau detalii despre o teamă de noapte. Dacă alegi livrarea pe email, folosim adresa introdusă pentru acel mesaj tranzacțional.</p><p className="mt-4">Lumi primește numai mesajele pe care alegi să le trimiți. Nu cere date sensibile și nu păstrează conversația ca profil sau istoric de cont în interfața noastră.</p></div></section>
      <section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">De ce le folosim</h2><p>Folosim aceste date pentru generarea textului, a ilustrației, a activităților și, la alegerea ta, pentru livrarea PDF-ului. De asemenea, păstrăm date tehnice și statistici agregate de funcționare pentru securitate, limitarea abuzurilor și îmbunătățirea produsului. Nu trimitem în telemetrie numele copilului, povestea, dedicația sau mesajele voastre.</p></section>
      <section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Furnizori tehnici</h2><p>Pentru funcționare folosim furnizori de infrastructură cloud, generare de conținut și livrare de email. Aceștia procesează informațiile numai în măsura necesară furnizării serviciului, în baza unor condiții contractuale și tehnice adecvate. Nu vindem datele și nu le folosim pentru publicitate comportamentală.</p></section>
      <section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Păstrare și siguranță</h2><p>Nu oferim bibliotecă de conturi și nu păstrăm o arhivă permanentă de povești sau PDF-uri. În beta, datele pot fi procesate temporar pentru generare, livrare, securitate și diagnosticare. După activarea comenzilor cu plată, configurația comenzii și materialul generat vor fi păstrate temporar pentru procesare, relivrare și acces printr-un link securizat, cu ștergerea automată a fișierelor după cel mult 31 de zile. Aplicăm măsuri tehnice și organizatorice rezonabile pentru a limita accesul și a proteja serviciul.</p></section>
      <section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Drepturile tale</h2><p>Poți cere informații despre datele procesate, corectare, ștergere, restricționare sau poți formula o obiecție, în limitele prevăzute de legislația aplicabilă. În perioada beta, trimite solicitarea la adresa de suport, cu suficiente detalii pentru identificarea mesajului sau livrării, fără să incluzi date sensibile suplimentare.</p></section>
      <section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Cookie-uri</h2><p>Detaliile despre stocarea locală și cookie-uri sunt disponibile în <Link href="/politica-cookie-uri" className="font-black text-brand-purple underline underline-offset-4">Politica de Cookie-uri</Link>. În prezent nu folosim cookie-uri de publicitate sau analiză identificabilă.</p></section>
    </div><a href={supportMailto("Solicitare confidențialitate - Povestea Mea Magică")} className="mx-auto mt-10 inline-flex max-w-5xl border-b border-brand-purple pb-1 text-sm font-black text-brand-purple">{publicContact.email}</a><p className="mx-auto mt-10 max-w-5xl text-sm font-semibold text-brand-navy/50">Ultima actualizare: 14 august 2026</p></section>
  </CommercialPage>;
}
