import type { Metadata } from "next";
import Link from "next/link";
import CommercialPage from "@/components/CommercialPage";
import { legalOperator, supportMailto } from "@/lib/publicContact";

export const metadata: Metadata = {
  title: "Politica de Rambursare | Povestea Mea Magică",
  description: "Cum tratăm rambursările și problemele de livrare pentru materialele digitale personalizate Povestea Mea Magică.",
  alternates: { canonical: "/politica-de-rambursare" },
};

export default function RefundPolicyPage() {
  return <CommercialPage eyebrow="Politica de rambursare" title="Reguli clare pentru materialele digitale personalizate." description="Explicăm transparent ce se întâmplă după plată, la livrarea imediată și atunci când ceva nu ajunge corect.">
    <section className="px-6 py-16 md:py-20"><div className="mx-auto max-w-5xl divide-y divide-brand-navy/15 border-y border-brand-navy/15 text-base font-medium leading-relaxed text-brand-navy/70"><section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Operator</h2><p><strong>{legalOperator.name}</strong>, CUI {legalOperator.cui}, este operatorul acestui serviciu digital.</p></section><section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Înainte de plată</h2><p>Vezi prețul final, conținutul produsului și modalitatea de livrare înainte de confirmarea comenzii. Pentru generarea imediată a materialului digital personalizat, pagina de plată solicită acordul tău expres pentru începerea furnizării și confirmarea faptului că, odată începută furnizarea, dreptul de retragere poate fi pierdut în condițiile legii.</p></section><section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Materiale personalizate</h2><p>După confirmarea plății și începerea generării pe baza alegerilor tale, comanda nu mai poate fi anulată automat ca un produs standard. Această regulă se aplică materialelor digitale furnizate imediat cu acordul prealabil expres și confirmarea informării privind pierderea dreptului de retragere.</p></section><section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Probleme de livrare</h2><p>Dacă PDF-ul nu se generează, nu se descarcă, emailul nu ajunge sau materialul nu reflectă alegerile confirmate, anunță-ne. Verificăm comanda și încercăm cu prioritate refacerea sau relivrarea fără cost. Atunci când problema nu poate fi remediată, analizăm rambursarea conform situației concrete și legislației aplicabile.</p></section><section className="grid gap-4 py-8 md:grid-cols-[.55fr_1.45fr]"><h2 className="font-serif text-3xl text-brand-navy">Cum ceri ajutor</h2><p>Scrie-ne de la adresa folosită la comandă și menționează materialul, data aproximativă și problema întâlnită. Nu include date sensibile despre copil.</p></section></div><div className="mx-auto mt-10 flex max-w-5xl flex-wrap gap-5"><a href={supportMailto("Ajutor pentru un material - Povestea Mea Magică")} className="border-b border-brand-purple pb-1 text-sm font-black text-brand-purple">Cere ajutor</a><Link href="/livrare-digitala" className="border-b border-brand-navy/30 pb-1 text-sm font-black text-brand-navy/70">Vezi livrarea digitală</Link></div><p className="mx-auto mt-10 max-w-5xl text-sm font-semibold text-brand-navy/50">Ultima actualizare: 21 august 2026</p></section>
  </CommercialPage>;
}
