import { KIT_COLORS, KIT_NAMES, type KitInput, type PremiumKit } from "./content.ts";
import { DIFFERENCE_ANSWERS, differencesSVG, envelopeSVG, escapeHtml as e, mazeSVG, shieldSVG } from "./graphics.ts";
import { shieldKeepsakePages } from "./shieldKeepsakes.ts";
import type { KitPageOrientation } from "./pageGeometry.ts";

export type KitPage = { title: string; html: string; orientation?: KitPageOrientation };
const heading = (kicker: string, title: string, sub = '') => `<header class="section-head"><div class="kicker">${e(kicker)}</div><h2>${e(title)}</h2>${sub ? `<p class="sub">${e(sub)}</p>` : ''}</header>`;
const body = (html: string) => `<div class="body">${html}</div>`;
const quote = (text: string) => `<div class="quote">„${e(text)}”</div>`;
const note = (text: string) => `<div class="note">${e(text)}</div>`;
const lumi = (text: string) => `<div class="dialogue"><img src="/lumi-guardian.webp" alt="Lumi"><p>${e(text)}</p></div>`;
const paragraphs = (texts: string[], cls = '') => texts.map(t => `<p class="${cls}">${e(t)}</p>`).join('');
const image = (src: string | undefined, cls: string, alt: string) => {
  // Images come only from bundled samples, private same-origin delivery, or generated raster data.
  const valid = src && (/^\/examples\/kits-v2\/[a-z-]+\.webp$/.test(src) || /^\/api\/orders\/[A-Za-z0-9_-]+\/asset\?/.test(src) || /^data:image\/(?:png|jpeg|webp);base64,[a-zA-Z0-9+/=]+$/.test(src));
  return valid ? `<img class="${cls}" src="${e(src)}" alt="${e(alt)}">` : `<div class="${cls}" role="img" aria-label="Ilustrație în pregătire"></div>`;
};

export function buildKitPages(input: KitInput, kit: PremiumKit, watermark = false): KitPage[] {
  const n = e(input.name), initial = input.name[0].toLocaleUpperCase('ro-RO');
  const coverSubtitle = kit.subtitle.includes(input.name) ? kit.subtitle : `${input.name} · ${kit.subtitle}`;
  const color = KIT_COLORS[input.favoriteColor as keyof typeof KIT_COLORS] || KIT_COLORS.pruna;
  const pages: KitPage[] = [];
  const add = (title: string, html: string, extra = '', orientation?: KitPageOrientation) => {
    const index = pages.length;
    pages.push({ title, orientation, html: `<article class="paper ${input.type === 'monster' ? 'atelier' : 'explorer'} ${extra}" data-orientation="${orientation || 'portrait'}" data-page-index="${index}" data-long-name="${input.name.length > 20}" data-keepsake-name="${input.name.length > 12 ? 'long' : input.name.length > 7 ? 'medium' : 'short'}" data-cover-long="${coverSubtitle.length > 80}" data-long-story="${kit.story.join('').length > 600}">${html}${extra === 'cover' ? '' : `<footer class="folio"><strong>Povestea Mea Magică · ${n}</strong><span>${String(index + 1).padStart(2,'0')}</span></footer>`}${watermark ? '<div class="sample-watermark">PREVIZUALIZARE</div>' : ''}</article>` });
  };
  const fixedTitle = input.type === 'monster' ? 'Atelierul<br>Scutului Magic' : 'Dosarul<br>Micului Explorator';
  add(KIT_NAMES[input.type], `<div class="cover-heading"><p class="brandline">POVESTEA MEA MAGICĂ</p><h2>${fixedTitle}</h2><span class="personal">${e(coverSubtitle)}</span></div>${image(kit.assets.cover,'cover-art',`Coperta personalizată pentru ${input.name}`)}<div class="cover-foot">O AVENTURĂ DE DESCOPERIT ÎMPREUNĂ</div>`, 'cover');
  add(kit.title, `${image(kit.assets.scene,'full-art',`O scenă din aventura lui ${input.name}`)}<div class="art-caption"><div class="kicker">ÎNCEPUTUL AVENTURII</div><h2>${e(kit.title)}</h2><div class="story-copy">${paragraphs(kit.story)}</div></div>`);
  if (input.type === 'monster') {
    add('Un scut numai al tău', heading('DESENAT PENTRU TINE','Trei repere. Un singur scut.','Scutul este un semn al ritualului vostru. Lucrurile care ajută sunt aproape și în viața reală.') + body(`<div class="shield-layout">${shieldSVG(initial,color)}<div class="shield-guide"><div><span class="small-label">Luna</span><p>${e(input.interest || 'Lumina de seară aleasă împreună.')}</p></div><div><span class="small-label">Litera ${e(initial)}</span><p>${n} are locul său în poveste.</p></div><div><span class="small-label">Trei stele</span><p>Privesc. Respir. Chem.</p></div></div></div><p class="inscription">„${e(kit.formula)}”</p>${lumi('Culoarea și inițiala îți aparțin. Alege locul în care păstrezi scutul.')}`));
    add('Laboratorul de lumină', heading('CURIOZITATE, ÎN DOZA VOASTRĂ','Ce putem descoperi împreună?','Un obiect cunoscut, o lumină obișnuită și un adult aproape. Copilul alege când ne oprim.') + body(`<div class="shadow-demo"><svg viewBox="0 0 180 155" aria-label="O lumină electrică, un reper familiar"><path d="M68 30h44l23 53H45Z" fill="#e9d99e" stroke="#85754e" stroke-width="2"/><path d="M90 83v46m-23 0h46" fill="none" stroke="#61546e" stroke-width="4"/><path d="m31 65-15-7m23 41-18 7m128-41 15-7m-23 41 18 7" stroke="#c29b5b" stroke-width="2"/></svg><div><p class="small-label shadow-mystery">Privește cu atenție.</p><p class="shadow-answer small-label">${e(kit.discovery)}</p></div><button type="button" data-kit-action="shadow">Dezvăluie descoperirea</button></div><div class="recipe-list">${kit.ritual.map((step,i)=>`<div class="recipe-step"><span>${i+1}</span><div><strong>${e(step.title)}</strong><p>${e(step.text)}</p></div></div>`).join('')}</div>${note('Nu trebuie să stingem lumina. Folosiți doar o lanternă electrică, manevrată de adult. Opriți jocul dacă devine neplăcut.')}`));
    add('Scutul de construit', heading('MÂINILE TALE DAU FORMA','Gata de construit.','Colorează scutul, apoi roagă un adult să-l decupeze. Îl puteți lipi pe carton subțire.') + body(`${shieldSVG(initial,color,true)}<div class="cut-labels"><span>Privesc împreună.</span><span>Respir încet.</span><span>Pot să te chem.</span></div><p class="tiny" style="margin-top:18px">Alege o formulă pentru spatele scutului. Păstrează-l lângă un reper familiar.</p>${lumi(kit.formula)}`));
    add('Trei carduri de apropiere', heading('PENTRU NOPTIERĂ','Cuvinte care țin aproape.','Un adult decupează cardurile. Alegeți unul pentru seara aceasta.') + body(`<div class="card-stack">${kit.ritual.map((s,i)=>`<div class="ritual-card"><span class="card-number">0${i+1}</span><h3>${e(s.title)}</h3><p>${e(s.text)}</p></div>`).join('')}</div><p class="tiny" style="margin-top:20px">Nu trebuie să memorezi formulele. Cuvintele voastre sunt la fel de bune.</p>`));
    add('Camera mea, pas cu pas', heading('CAMERA TA','Locurile noastre de seară.','Desenează camera și unește locurile în ordinea în care le vizitați seara.') + body(`<div class="map-legend"><div class="stop"><svg viewBox="0 0 38 38"><path d="M4 28V13m0 10h27v11m-27-4h27M7 22v-7h7v7m1-5h13v6"/></svg>Patul meu</div><span>→</span><div class="stop"><svg viewBox="0 0 38 38"><path d="m12 5-6 14h26L26 5ZM19 19v13m-7 0h14"/></svg>Lumina mea</div><span>→</span><div class="stop"><svg viewBox="0 0 38 38"><circle cx="19" cy="10" r="5"/><path d="M8 32v-6c0-10 22-10 22 0v6"/></svg>Adultul meu de încredere</div></div><div class="room-map">Aici desenezi camera ta.</div><div class="fear-box">Aici apare umbra sau sunetul care mă neliniștește:<span></span></div><p class="tiny" style="margin-top:15px">Reperul ales: ${e(input.context || 'camera mea')}. Adultul meu: ${e(input.trustedAdult)}.</p>`));
    add('Șapte seri fără grabă', heading('CÂT NE PLACE, CÂND NE PLACE','Șapte întâlniri cu lumina.','Bifează o seară în care ați încercat ceva împreună. Puteți repeta sau sări peste un pas.') + body(`<div class="seven-days">${[['Privește','Numim un obiect cunoscut.'],['Alege','Alegem lumina care ne place.'],['Desenează','Punem un semn pe scut.'],['Povestește','Ce am descoperit împreună?'],['Respiră','Expirăm lent, fără să forțăm.'],['Cheamă','Repetăm cum cerem apropiere.'],['Păstrează','Alegem gestul de mâine.']].map((x,i)=>`<div class="day-row"><b>${i+1}</b><div><strong>${x[0]}</strong><p>${x[1]}</p></div><button class="day-check" type="button" data-kit-action="day" aria-label="Marchează seara ${i+1}" aria-pressed="false"></button></div>`).join('')}</div>${note('O seară cu emoții nu șterge nimic. Calendarul păstrează timpul vostru împreună.')}`));
    add('Scrisoarea lui Lumi', heading('O SCRISOARE NUMAI PENTRU TINE',`${input.name}, păstrăm descoperirea.`) + body(`<div class="letter-salute">Pentru ${n},</div>${paragraphs(kit.letter,'letter-paragraph')}${quote(kit.formula)}<div class="signed"><img src="/lumi-guardian.webp" alt="Lumi"><div><strong>Cu drag, Lumi</strong><p class="tiny">Păzitoarea lanternei</p></div></div>`), 'hand-letter');
    add('Pentru adult', heading('PENTRU ADULT','O seară bună începe cu apropiere.') + body(`<p>${e(kit.parentMessage)}</p><div class="recipe-list">${kit.ritual.map((s,i)=>`<div class="recipe-step"><span>${i+1}</span><div><strong>${e(s.title)}</strong><p>${e(s.text)}</p></div></div>`).join('')}</div>${note('Scutul, certificatul și rețeta sunt jocuri simbolice. Nu protejează de pericole reale și nu promit dispariția fricii. Nu înlocuiesc sprijinul unui specialist atunci când acesta este necesar.')}${quote('Sunt aici. Spune-mi ce ai nevoie să facem împreună.')}`));
  } else {
    const clue = (i: number, text: string) => `<div class="clue-token"><b>${kit.codeWord[i]}</b><p>${e(text)}</p></div>`;
    add('Radarul exploratorului', heading('PROBA 01 · OBSERVĂ','Locul ascunde patru indicii.','Privește din locul tău. Dacă un indiciu lipsește, îl poți inventa într-un desen.') + body(`<div class="evidence">${kit.radar.map((x,i)=>`<div class="evidence-item"><span>INDICIU 0${i+1}</span><h3>${e(x.title)}</h3><p>${e(x.text)}</p><div class="drawing-line"></div></div>`).join('')}</div>${clue(0,'Prima literă este a ta. Adultul o poate scrie pe bilet.')}${lumi('Un loc obișnuit poate deveni o lume întreagă dacă îl privești cu atenție.')}`));
    add('Traseul curierului', heading('PROBA 02 · URMĂREȘTE','Găsește drumul până la plic.','Pornește de la punctul corai și ajungi la plicul verde, fără să treci peste pereți.') + body(`<div class="maze-area">${mazeSVG(input.difficulty)}</div><button type="button" class="solve-button" data-kit-action="maze">Arată traseul</button>${clue(1,'A doua literă a ajuns la destinație. O așezăm lângă prima.')}<p class="tiny" style="margin-top:13px">Poți urmări întâi cu degetul. Adultul ajută atunci când copilul cere.</p>`));
    add('Ce s-a schimbat?', heading('PROBA 03 · COMPARĂ','Lumea s-a schimbat cât am clipit.','Descoperă trei diferențe între imagini și încercuiește-le pe planșă.') + body(`<div class="difference-grid">${differencesSVG(false)}${differencesSVG(true)}</div><button type="button" class="solve-button" data-kit-action="differences">Verifică diferențele</button>${clue(2,`Avem toate literele: ${kit.codeWord.split('').join(' · ')}. Adultul citește destinația din poveste.`)}`));
    add('Invenția ta', heading('ATELIERUL TĂU','O invenție care duce un secret.',kit.drawingPrompt) + body(`<div class="creative-area"><svg viewBox="0 0 450 290" aria-label="Plic de completat și colorat"><g fill="none" stroke="#487869" stroke-width="2.5"><rect x="115" y="100" width="220" height="120" rx="2"/><path d="m115 100 110 74 110-74M115 220l76-70m144 70-76-70"/><circle cx="225" cy="168" r="14"/><path d="M70 258h310" stroke-dasharray="5 5"/></g></svg></div><div class="creative-bottom"><div>Numele invenției:<div class="drawing-line"></div></div><div>Puterea ei specială:<div class="drawing-line"></div></div></div>${lumi('Completează desenul cu roți, aripi sau o idee numai a ta. Nu există o singură soluție.')}`));
    add('Misiuni de buzunar', heading('DE PĂSTRAT · DE DECUPAT','Patru misiuni în buzunar.','Un adult decupează biletele. Alegeți unul când mai aveți câteva minute de așteptat.') + body(`<div class="tickets">${kit.tickets.map((x,i)=>`<div class="ticket"><b>MISIUNEA 0${i+1}</b><h3>${e(x.title)}</h3><p>${e(x.text)}</p><footer>Împreună · fără grabă</footer></div>`).join('')}</div><p class="tiny" style="margin-top:20px">Nu sunt teste. Opriți-vă când momentul vostru de așteptare s-a încheiat.</p>`));
    add('Plicul se deschide', heading('CAZ REZOLVAT','Trei litere. O descoperire.') + body(`<div class="code-strip" style="justify-content:center">${kit.codeWord.split('').map(x=>`<span class="code-cell">${x}</span>`).join('')}</div>${paragraphs(kit.ending.slice(0,1))}${quote(kit.discovery)}${paragraphs(kit.ending.slice(1))}${envelopeSVG(input.name)}<p class="tiny">Numele lumii noastre: __________________________________</p>`));
    add('Răspunsurile adultului', heading('PENTRU ADULT','Tu citești. Copilul descoperă.','Literele sunt indicii citite împreună, nu un test de citire.') + body(`<div class="answers"><div class="answer-row"><b>${kit.codeWord[0]}</b><div><strong>Radarul</strong><p>Răspunsuri deschise. Acceptăm un obiect potrivit sau un desen inventat.</p></div></div><div class="answer-row"><b>${kit.codeWord[1]}</b><div><strong>Traseul curierului</strong><div class="answer-maze">${mazeSVG(input.difficulty,true)}</div><p>Soluția verificată pornește din stânga sus și se încheie în dreapta jos.</p></div></div><div class="answer-row"><b>${kit.codeWord[2]}</b><div><strong>Trei diferențe, exact</strong><p>${DIFFERENCE_ANSWERS.map(e).join(' ')}</p></div></div></div>${note(kit.parentMessage)}<p class="tiny" style="margin-top:16px">Rămânem în locul ales. Nu folosim obiecte fierbinți, ascuțite sau fragile. Putem opri jocul oricând.</p>`));
    add('Explorator de lumi mici', heading('ÎNCHEIAT CU IMAGINAȚIE',`${input.name}, explorator de lumi mici.`) + body(`<div class="award-initial">${e(initial)}</div><p>Ai observat. Ai întrebat.<br>Ai inventat un drum nou.</p><p>Păstrează ideile tale pentru următoarea ieșire.</p><div class="explorer-keepsake"><span>DIN JURNALUL EXPEDIȚIEI</span><div>Locul pe care l-am descoperit:<i></i></div><div>O idee pe care vreau să o păstrez:<i></i></div></div><p class="tiny">Semnătura exploratorului: ______________________</p>`), 'closing');
  }
  if (input.type === 'monster') {
    for (const page of shieldKeepsakePages(input, kit)) add(page.title, page.html, page.extra, page.orientation);
  }
  return pages;
}
